// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReTo.DataAccess.Models;

/// <summary>
/// 帳戶密碼變更記錄
/// </summary>
public partial class AccountPasswordChange
{
    /// <summary>
    /// 流水編號
    /// </summary>
    public int SequentialId { get; set; }

    /// <summary>
    /// 唯一識別碼
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 使用者識別碼
    /// </summary>
    public Guid AccountId { get; set; }

    /// <summary>
    /// 變更時間
    /// </summary>
    public DateTime ChangeTime { get; set; }

    /// <summary>
    /// 原始密碼
    /// </summary>
    public string OriginalPassword { get; set; }

    /// <summary>
    /// 客戶端 IP 位置
    /// </summary>
    public string ClientIp { get; set; }

    /// <summary>
    /// 客戶端代理程式
    /// </summary>
    public string UserAgent { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    public virtual Account Account { get; set; }
}