// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReTo.DataAccess.Models;

/// <summary>
/// 應用程式帳戶
/// </summary>
public partial class Account
{
    /// <summary>
    /// 流水編號
    /// </summary>
    public int SequentialId { get; set; }

    /// <summary>
    /// 唯一識別碼
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string Username { get; set; }

    /// <summary>
    /// 密碼
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// 密碼有效期限
    /// </summary>
    public DateTime? PasswordExpireAt { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<AccountLogin> AccountLogins { get; set; } = new List<AccountLogin>();

    public virtual ICollection<AccountPasswordChange> AccountPasswordChanges { get; set; } = new List<AccountPasswordChange>();

    public virtual User User { get; set; }
}