// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReTo.DataAccess.Models;

/// <summary>
/// 應用程式參數
/// </summary>
public partial class Option
{
    /// <summary>
    /// 流水編號
    /// </summary>
    public int SequentialId { get; set; }

    /// <summary>
    /// 唯一識別碼
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 參數名稱
    /// </summary>
    public string OptionName { get; set; }

    /// <summary>
    /// 參數值
    /// </summary>
    public string OptionValue { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 最後更新者識別碼
    /// </summary>
    public Guid? UpdaterId { get; set; }

    public virtual User Updater { get; set; }
}