// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ReTo.DataAccess.Models;

public partial class ReToContext : DbContext
{
    public ReToContext(DbContextOptions<ReToContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AccountLogin> AccountLogins { get; set; }

    public virtual DbSet<AccountPasswordChange> AccountPasswordChanges { get; set; }

    public virtual DbSet<Option> Options { get; set; }

    public virtual DbSet<ShortUrl> ShortUrls { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("應用程式帳戶"));

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("唯一識別碼")
                .HasColumnName("ID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("建立時間")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt)
                .HasComment("刪除時間")
                .HasColumnType("datetime");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("是否啟用");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("密碼");
            entity.Property(e => e.PasswordExpireAt)
                .HasComment("密碼有效期限")
                .HasColumnType("datetime");
            entity.Property(e => e.SequentialId)
                .ValueGeneratedOnAdd()
                .HasComment("流水編號")
                .HasColumnName("SequentialID");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("帳號");
        });

        modelBuilder.Entity<AccountLogin>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("帳戶登入記錄"));

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("唯一識別碼")
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasComment("使用者識別碼")
                .HasColumnName("AccountID");
            entity.Property(e => e.ClientIp)
                .IsRequired()
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasComment("客戶端 IP 位置")
                .HasColumnName("ClientIP");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("建立時間")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpireAt)
                .HasComment("有效期限")
                .HasColumnType("datetime");
            entity.Property(e => e.IsRevoked).HasComment("是否作廢登入");
            entity.Property(e => e.IsSuccessful).HasComment("是否成功登入");
            entity.Property(e => e.LoginTime)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("登入時間")
                .HasColumnType("datetime");
            entity.Property(e => e.SequentialId)
                .ValueGeneratedOnAdd()
                .HasComment("流水編號")
                .HasColumnName("SequentialID");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");
            entity.Property(e => e.UserAgent)
                .IsRequired()
                .IsUnicode(false)
                .HasComment("客戶端代理程式");

            entity.HasOne(d => d.Account).WithMany(p => p.AccountLogins)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_AccountLogins_Accounts");
        });

        modelBuilder.Entity<AccountPasswordChange>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("帳戶密碼變更記錄"));

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("唯一識別碼")
                .HasColumnName("ID");
            entity.Property(e => e.AccountId)
                .HasComment("使用者識別碼")
                .HasColumnName("AccountID");
            entity.Property(e => e.ChangeTime)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("變更時間")
                .HasColumnType("datetime");
            entity.Property(e => e.ClientIp)
                .IsRequired()
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasComment("客戶端 IP 位置")
                .HasColumnName("ClientIP");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("建立時間")
                .HasColumnType("datetime");
            entity.Property(e => e.OriginalPassword)
                .IsRequired()
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasComment("原始密碼");
            entity.Property(e => e.SequentialId)
                .ValueGeneratedOnAdd()
                .HasComment("流水編號")
                .HasColumnName("SequentialID");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");
            entity.Property(e => e.UserAgent)
                .IsRequired()
                .IsUnicode(false)
                .HasComment("客戶端代理程式");

            entity.HasOne(d => d.Account).WithMany(p => p.AccountPasswordChanges)
                .HasForeignKey(d => d.AccountId)
                .HasConstraintName("FK_AccountPasswordChanges_Accounts");
        });

        modelBuilder.Entity<Option>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("應用程式參數"));

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("唯一識別碼")
                .HasColumnName("ID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("建立時間")
                .HasColumnType("datetime");
            entity.Property(e => e.OptionName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("參數名稱");
            entity.Property(e => e.OptionValue)
                .IsUnicode(false)
                .HasComment("參數值");
            entity.Property(e => e.SequentialId)
                .ValueGeneratedOnAdd()
                .HasComment("流水編號")
                .HasColumnName("SequentialID");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdaterId)
                .HasComment("最後更新者識別碼")
                .HasColumnName("UpdaterID");

            entity.HasOne(d => d.Updater).WithMany(p => p.Options)
                .HasForeignKey(d => d.UpdaterId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Options_Users");
        });

        modelBuilder.Entity<ShortUrl>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Urls");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("唯一識別碼")
                .HasColumnName("ID");
            entity.Property(e => e.ClientIp)
                .IsRequired()
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasComment("客戶端 IP 位置")
                .HasColumnName("ClientIP");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("建立時間")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt)
                .HasComment("刪除時間")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpireAt)
                .HasComment("有效期限")
                .HasColumnType("datetime");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("是否啟用");
            entity.Property(e => e.OriginalUrl)
                .IsRequired()
                .IsUnicode(false)
                .HasComment("原始網址");
            entity.Property(e => e.SequentialId)
                .ValueGeneratedOnAdd()
                .HasComment("流水編號")
                .HasColumnName("SequentialID");
            entity.Property(e => e.ShortCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("短網址代碼");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");
            entity.Property(e => e.UserAgent)
                .IsRequired()
                .IsUnicode(false)
                .HasComment("客戶端代理程式");
            entity.Property(e => e.UserId)
                .HasComment("使用者識別碼")
                .HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.ShortUrls)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_ShortUrls_Users");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable(tb => tb.HasComment("使用者"));

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasComment("唯一識別碼")
                .HasColumnName("ID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasComment("建立時間")
                .HasColumnType("datetime");
            entity.Property(e => e.DeletedAt)
                .HasComment("刪除時間")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("電子信箱");
            entity.Property(e => e.IsEmailVerified).HasComment("是否完成信箱驗證");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("名稱");
            entity.Property(e => e.SequentialId)
                .ValueGeneratedOnAdd()
                .HasComment("流水編號")
                .HasColumnName("SequentialID");
            entity.Property(e => e.UpdatedAt)
                .HasComment("最後更新時間")
                .HasColumnType("datetime");

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.User)
                .HasForeignKey<User>(d => d.Id)
                .HasConstraintName("FK_Users_Accounts");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}