// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class ShortUrl
{
    /// <summary>
    /// 流水編號
    /// </summary>
    public int SequentialId { get; set; }

    /// <summary>
    /// 唯一識別碼
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 使用者識別碼
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// 短網址代碼
    /// </summary>
    public string ShortCode { get; set; }

    /// <summary>
    /// 原始網址
    /// </summary>
    public string OriginalUrl { get; set; }

    /// <summary>
    /// 客戶端 IP 位置
    /// </summary>
    public string ClientIp { get; set; }

    /// <summary>
    /// 客戶端代理程式
    /// </summary>
    public string UserAgent { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 有效期限
    /// </summary>
    public DateTime? ExpireAt { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    public DateTime? DeletedAt { get; set; }

    public virtual User User { get; set; }
}