// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReTo.DataAccess.Models;

/// <summary>
/// 使用者
/// </summary>
public partial class User
{
    /// <summary>
    /// 流水編號
    /// </summary>
    public int SequentialId { get; set; }

    /// <summary>
    /// 唯一識別碼
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 電子信箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 是否完成信箱驗證
    /// </summary>
    public bool IsEmailVerified { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 最後更新時間
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    public DateTime? DeletedAt { get; set; }

    public virtual Account IdNavigation { get; set; }

    public virtual ICollection<Option> Options { get; set; } = new List<Option>();

    public virtual ICollection<ShortUrl> ShortUrls { get; set; } = new List<ShortUrl>();
}